preserve_hierarchy: true
commit_message: "Changed: New (%language%) translations"
append_commit_message: false
pull_request_labels:
  - translations
files:
  - source: /src/locales/*.json
    translation: /src/locales/%two_letters_code%.json
    type: json